declare const _default: (tokens?: any) => {
    ZERO_ADDRESS: string;
    Owner: any;
    Governor: any;
    EscapeHatchManager: any;
    EscapeHatchTokenHolder: any;
    LST: any;
    DAI: any;
    WETH: any;
    PriceFeed: any;
    CurrencyDao: any;
    InterestPoolDao: any;
    UnderwriterPoolDao: any;
    MarketDao: any;
    ShieldPayoutDao: any;
    PoolNameRegistry: any;
    PositionRegistry: any;
    CurrencyPool: any;
    InterestPool: any;
    UnderwriterPool: any;
    ERC20PoolToken: any;
    PriceOracle: any;
    CollateralAuctionCurve: any;
    MultiFungibleToken: any;
    ProtocolDao: any;
};
export default _default;
